version: '3'

services:
  app:
    build:
      context: .
    restart: on-failure
    depends_on:
      - redis
    command: python3 ./app/main.py

  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: